name: Build on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:v2.3-branch
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check if west is in PATH
        run: |
          echo $PATH
          which west || true

      - name: Install west if not available
        run: |
          which west || pip3 install --user west

      - run: west build -b nrf52840dk_nrf52840 -p

