name: Build on push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:v2.3-branch
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: west build -b thingy53_nrf5340_cpuapp -p
