name: Build on push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  container-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
		# Container
      container: 
	      image: nordicplayground/nrfconnect-sdk:v2.3-branch

    steps:
      - uses: actions/checkout@v3
      - name: Build for thingy53
        run: west build always -b thingy53_nrf5340_cpuapp -p

