name: Build on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:v2.4-branch
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: west init
      - run: west update
      - run: west build -p always -b adafruit_feather_nrf52840
